In [1]:
import numpy as np
import pandas as pd

In [2]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.544190  0.365644 -0.116569  0.834654
2013-01-02  0.620892 -0.425064  1.203328 -0.192065
2013-01-03  0.461293 -0.187658  0.060559 -0.415219
2013-01-04 -1.985954  0.341642  0.547061  2.553895
2013-01-05 -0.617066 -0.429884  0.723192 -0.444881
2013-01-06  0.798963 -1.199519  0.944710  0.059183

In [7]:
df.to_numpy()

array([[-0.54419008,  0.36564391, -0.11656927,  0.83465402],
       [ 0.62089198, -0.42506436,  1.20332796, -0.1920646 ],
       [ 0.46129253, -0.18765845,  0.06055925, -0.41521878],
       [-1.98595401,  0.34164167,  0.54706115,  2.55389541],
       [-0.61706612, -0.429884  ,  0.72319232, -0.44488133],
       [ 0.79896254, -1.19951868,  0.9447104 ,  0.05918316]])

In [8]:
df.sort_values(by="B")

                   A         B         C         D
2013-01-06  0.798963 -1.199519  0.944710  0.059183
2013-01-05 -0.617066 -0.429884  0.723192 -0.444881
2013-01-02  0.620892 -0.425064  1.203328 -0.192065
2013-01-03  0.461293 -0.187658  0.060559 -0.415219
2013-01-04 -1.985954  0.341642  0.547061  2.553895
2013-01-01 -0.544190  0.365644 -0.116569  0.834654

In [9]:
df["A"]

2013-01-01   -0.544190
2013-01-02    0.620892
2013-01-03    0.461293
2013-01-04   -1.985954
2013-01-05   -0.617066
2013-01-06    0.798963
Freq: D, Name: A, dtype: float64

In [ ]:
# Выборка по строкам
df[0:2]

                   A         B         C         D
2013-01-01 -0.544190  0.365644 -0.116569  0.834654
2013-01-02  0.620892 -0.425064  1.203328 -0.192065

In [16]:
df1 = pd.DataFrame(np.random.randn(6, 4),
                   index=list('abcdef'),
                   columns=list('ABCD'))
df1

          A         B         C         D
a  0.415285 -0.550873  1.648065  0.680807
b  1.291655  0.097590 -1.388996  0.642056
c -0.108451  0.682628  1.561521  1.635270
d  0.595875 -0.568023  2.373054 -1.160195
e -2.177683 -0.913379  1.016517 -0.496615
f  1.068725 -1.192386 -0.656085 -0.647204

## loc
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.lo

In [35]:
# loc - выборка по строкам. Работает с метками (по существу с индексами),
# которые, если надо взять несколько строк, объдиняются в список.
# Если надо ограничить вывод данных по столбцам - то синтаксис аналогичен.

# df1.loc[['a', 'b', 'd'], ['A','D']] # -------- Столбцы на выбор. 
# df1.loc[['a', 'b', 'd'], 'B':'C']   # -------- Столбцы по порядку.
df1.loc['a', 'B']                     # -------- Одно конкретное значение.

-0.5508726868430001

In [46]:

# # Выборка по условию

# df1.loc[df1['A'] > 0, ['A', 'B']]
df1.loc[(df1['A'] > 0) & (df1['B'] < 0), ['A', 'B']]

          A         B
a  0.415285 -0.550873
d  0.595875 -0.568023
f  1.068725 -1.192386

In [ ]:
# Присвоение значения: первая переменная - "для кого", вторая - "кому".

# df1.loc['a', 'A'] = 0.5
df1.loc[df1['A'] == 0.5] = 0.42   # можно +0.2 и т.п. операции.
df1

          A         B         C         D
a  0.420000  0.420000  0.420000  0.420000
b  1.291655  0.097590 -1.388996  0.642056
c -0.108451  0.682628  1.561521  1.635270
d  0.595875 -0.568023  2.373054 -1.160195
e -2.177683 -0.913379  1.016517 -0.496615
f  1.068725 -1.192386 -0.656085 -0.647204

## iloc
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html

In [ ]:
# iloc - та же выборка по строкам. Работает с порядковыми номерами строк (0, 1, ...),
# Синтаксис ":". 
# Если надо ограничить вывод данных по столбцам - то синтаксис аналогичен.

df1.iloc[0:2, :2]

          A         B
a  0.415285 -0.550873
b  1.291655  0.097590

In [51]:
import re

In [55]:
ttt = "The rain in Spain"
x = re.sub("\s", "9", ttt, 1)
print(x)

The9rain in Spain

In [61]:
import math
x = 1
result = math.log(x)
result

0.0